def tuple_slice_ops():
    print('Enter your tuple value :')
    my_tuple = ()
    my_tuple = (int(item) for item in input("Enter the list numeric values : ").split())
    my_tuple1 = ()
    my_tuple2 = ('Happy','Family','Joy','Peace')
    my_tuple1 = (item for item in input("Enter the list string values : ").split())
    tuple =  (*my_tuple, *my_tuple1, *my_tuple2)
    print(tuple)

    print(f'Your tuple is : ', tuple)
    print('-------------------------------------')
    print("Slice of the tuple '{1}' after removing first and last items'{0}'".format(tuple[1:-1], tuple))
    print('-------------------------------------')
    print("Slice of the tuple '{1}' after removing first 2 items '{0}'".format(tuple[2:], tuple))
    print('-------------------------------------')
    print("Slice of the tuple '{1}' after removing last 2 items '{0}'".format(tuple[:-2],tuple))
    print('-------------------------------------')
    print("Mid index of the tuple is is {0}".format(int(len(tuple) / 2)))
    print('-------------------------------------')
    mi = int(len(tuple) / 2)
    print("First half of the tuple is '{1}' is '{0}'".format(tuple[:mi], list))
    print("Second half of the tuple is '{1}' is '{0}'".format(tuple[mi:], list))
    print('-------------------------------------')

tuple_slice_ops()